name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze (.NET 9)
    runs-on: windows-latest

    steps:
      # --- Requerido por SonarCloud (java 17) ---
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # --- Checkout del repo ---
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Instalar .NET 9 SDK ---
      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # --- Cache Sonar ---
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      # --- Instalar Sonar Scanner como dotnet tool ---
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory -Force
          dotnet tool install dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner

      # --- Construcción + Análisis ---
      - name: Build and analyze
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          $scanner = "${{ runner.temp }}\scanner\dotnet-sonarscanner.exe"
          
          & $scanner begin `
            /k:"jperezdev_devops-pipeline-demo" `
            /o:"jperezdev" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.cs.dotcover.reportsPaths="coverage.dotcover.xml"

          dotnet build --configuration Release

          & $scanner end `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
